//
// FlushMouseSettings.idl for FlushMouseSettings
//
//		Copyright (C) 1993- JeffyTS. All rights reserved.
//		Licensed under the GPL-2.0 License.
//
// No.	  Date			Name			Reason & Document
// -------+-----------+-----------+-------------------------------------------- -
// #0000		2022/07/16  JeffyTS  	New edit.
//

namespace FlushMouseSettings
{
}

/* = EOF = */
