// MojoWindow.idl for FlushMouseSettings
//		Copyright (C) 1993 JeffyTS
//
//	  
// No.	  Date			Name			Reason & Document
// -------+-----------+-----------+-------------------------------------------- -
// #0000	2022/07/16  JeffyTS  	New edit.
//

namespace FlushMouseSettings
{
	[default_interface]
	runtimeclass MojoWindow : Microsoft.UI.Xaml.Window
	{
		MojoWindow();
	}
}
